### ISSUE TITLE
a

### ISSUE THREAD

**Issue by tppk** [trufflesuite/truffle-teams#5] opened 2019-08-16 05:30 UTC
Compiling your contracts...
===========================
Error executing vyper:
/bin/sh: 1: vyper: not found

Truffle v5.0.10 (core: 5.0.10)
Node v11.13.0

**Comment by tppk** [comment] 2019-08-16 05:30
[https://coincolors.co/wp-content/uploads/2018/05/btc-price-CoinColors.co_.jpg](url)

**Comment by nicholasjpaterno** [comment] 2019-08-16 15:44
@tppk Please do not post masked links or I'll be forced to block your participation in this repository.

**Comment by seesemichaelj** [comment] 2019-08-16 16:52
Duplicate of #4

**Closed by seesemichaelj** 2019-08-16 16:52 UTC
